(**************************************************************************)
(*                                                                        *)
(*                                 OCaml                                  *)
(*                                                                        *)
(*                       Pierre Chambart, OCamlPro                        *)
(*           Mark Shinwell and Leo White, Jane Street Europe              *)
(*                                                                        *)
(*   Copyright 2013--2019 OCamlPro SAS                                    *)
(*   Copyright 2014--2019 Jane Street Group LLC                           *)
(*                                                                        *)
(*   All rights reserved.  This file is distributed under the terms of    *)
(*   the GNU Lesser General Public License version 2.1, with the          *)
(*   special exception on linking described in the file LICENSE.          *)
(*                                                                        *)
(**************************************************************************)

(** Translate Lambda code to Cmm using Flambda 2. This function is not currently
    re-entrant. *)
val lambda_to_cmm :
  ppf_dump:Format.formatter ->
  prefixname:string ->
  machine_width:Target_system.Machine_width.t ->
  keep_symbol_tables:bool ->
  Lambda.program ->
  Cmm.phrase list

(** Resume compilation from the LTO sections of .cmx files (generated by
    -support-lto) and a .ltosol file (from -reaper-solve), producing Cmm code
    for one compilation unit at a time.

    Applying the first three arguments loads and deserialises the .ltosol file,
    creating the state shared by a batch of rebuilds. The returned function
    rebuilds one unit from its .cmx file, whose contents are passed as
    [paused_unit_infos]; it must be called once per member of the batch, in any
    order, with [Compilenv.reset] having been called for the member first.
    [batch_members] must be the compilation units of the batch.

    The identifier tables are shared by the whole batch, so
    [keep_symbol_tables:false], which resets them after producing the Cmm code,
    is only allowed for the last member. *)
val reaped_flambda2_to_cmm :
  machine_width:Target_system.Machine_width.t ->
  ltosol_filename:string ->
  batch_members:Compilation_unit.t list ->
  keep_symbol_tables:bool ->
  cmx_filename:string ->
  paused_unit_infos:Cmx_format.unit_infos ->
  ppf_dump:Format.formatter ->
  prefixname:string ->
  Cmm.phrase list

(** Produce a whole-program Reaper solution from the dependency graphs in the
    given .cmx files generated by -support-lto and write it to [ltosol_file]. *)
val reaper_lto_solve : cmx_files:string list -> ltosol_file:string -> unit

type flambda_result =
  { flambda : Flambda_unit.t;
    all_code : Exported_code.t;
    offsets : Exported_offsets.t;
    reachable_names : Flambda2_nominal.Name_occurrences.t
  }

(** Translate Lambda code into (potentially Simplified) Flambda 2. This function
    is not currently re-entrant. *)
val lambda_to_flambda :
  ppf_dump:Format.formatter ->
  prefixname:string ->
  machine_width:Target_system.Machine_width.t ->
  Lambda.program ->
  flambda_result

val flambda_to_flambda :
  ppf_dump:Format.formatter ->
  prefixname:string ->
  machine_width:Target_system.Machine_width.t ->
  code_slot_offsets:Slot_offsets.t Flambda2_identifiers.Code_id.Map.t ->
  Flambda_unit.t ->
  flambda_result

val reset_symbol_tables : unit -> unit

val get_module_info :
  Compilation_unit.t -> Flambda2_cmx.Flambda_cmx_format.t option

(** Used in toplevel expect test tool *)
val register_compilation_unit_callback : (Compilation_unit.t -> unit) -> unit
